version: '3.5'

networks:
  app-tier:
    driver: bridge

services:

  backend:
    build: .
    depends_on:
      - db
    restart: on-failure
    ports:
      - "21080:80"
    volumes:
      - .composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app
    networks:
      - app-tier

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - .composer-docker/mysql:/var/lib/mysq
    environment:
      - MYSQL_DATABASE=mybooking
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    networks:
      - app-tier

  db_test:
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - .composer-docker/mysql_test:/var/lib/mysq
    environment:
      - MYSQL_DATABASE=mybooking_test
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    networks:
      - app-tier
